FROM mcr.microsoft.com/devcontainers/cpp:ubuntu-22.04
RUN apt-get update && \
    apt-get install -y wget git bash make patch gzip texinfo tar nasm autoconf bison flex libmpc-dev grub-pc-bin xorriso gperf autopoint help2man libfuse-dev rsync parted qemu-system
